config/routes.rb
NewDay0::Application.routes.draw do
  use_doorkeeper
  root :to => 'home#index'
  devise_for :users, :controllers => { :ajax_registrations => "devise/ajax_registrations", :ajax_sessions => "devise/ajax_sessions"  }
  devise_scope :user do
    get 'ajax_new' => 'devise/ajax_registrations#new', as: 'ajax_registration_new'
    get 'json_new' => 'devise/ajax_registrations#json_new', as: 'json_registration_new'
    post 'ajax_create' => 'devise/ajax_registrations#create', as: 'ajax_registration_create'
    get 'ajax_session_new' => 'devise/ajax_sessions#new', as: 'ajax_session_new'
    post 'ajax_session_create' => 'devise/ajax_sessions#create', as: 'ajax_session_create'

  end

  get 'authed_request' => 'home#authed_request', as: 'authed_request'

  mount Provider::Engine, at: '/provider', :as => 'provider_engine'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, styles: { thumb: '50x50#' }
  # Validate content type
  validates_attachment_content_type :image, :content_type => /\Aimage/
  # Validate filename
  validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/]
  
  # Assigns the image specified by the url to the user's paperclip managed image attrtibute
  # paperclip requires that the extension and mime type match
  # this code will rewrite the temp file to have an extension if one is missing
  # @param [String] url - the full URL of the image to be assigned as the user's image
  def image_from_url(url)
    unless url.blank?
      begin      
        extname = File.extname(url)
        basename = File.basename(url, extname)
        file = Tempfile.new([basename, extname])
        file.binmode
        open(URI.parse(url)) do |data|
          file.write data.read
        end
        file.rewind
        if extname.blank?
          mime = `file --mime -br #{file.path}`.strip
          mime = mime.gsub(/^.*: */,"")
          mime = mime.gsub(/;.*$/,"")
          mime = mime.gsub(/,.*$/,"")
          extname = "."+mime.split("/")[1]
          File.rename(file.path, file.path+extname)
          file = File.new(file.path+extname)
        end
      rescue Exception => e
        logger.info "EXCEPTION IMPORTING PHOTO"
        logger.info "for user: #{self.inspect}"
        logger.info "error: #{e.message}"
      end
      begin      
        self.image = file
      rescue Exception => e
        logger.info "EXCEPTION STORING PHOTO"
        logger.info "for user: #{self.inspect}"
        logger.info "error: #{e.message}"
      end
    end
  end

  
  # Takes in auth credentials returned from a Facebook login and finds or creates the User
  # If a matching User is found in the system, that User is returned
  # If no matching User is found in the system, a new User is created
  # @param [OmniAuth::AuthHash] auth - the returned hash of user information from the facebook login request
  def self.find_for_facebook_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      unless user.persisted?
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
        (user.first_name = auth.info.first_name) if auth.has_key?("info") && auth.info.has_key?("first_name")
        (user.last_name = auth.info.last_name) if auth.has_key?("info") && auth.info.has_key?("last_name")
        (user.username = auth.info.nickname) if auth.has_key?("info") && auth.info.has_key?("nickname")
        if auth.has_key?("extra") && auth.extra.has_key?("raw_info") && auth.extra.raw_info.has_key?("gender")
          user.gender = auth.extra.raw_info.gender
        end
        if auth.has_key?("extra") && auth.extra.has_key?("raw_info") && auth.extra.raw_info.has_key?("locale")
          user.locale = auth.extra.raw_info.locale
        end
        if auth.has_key?("extra") && auth.extra.has_key?("raw_info") && auth.extra.raw_info.has_key?("age_range")
          user.age_range = auth.extra.raw_info.locale 
        end
        user.image_from_url auth.info.image
        user.save!
      end
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  respond_to :json, :html

  after_filter :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  protected

  def verified_request?
    super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
  end

end

app/controllers/concerns/keeperable.rb
# Probably call this Providerable, and pass the provider name into these methods to make them generic

module Keeperable
  extend ActiveSupport::Concern

  def manage_doorkeeper_token(resource, application_id)
      # Create an OAuth2 Access token to be rendered
      token = Doorkeeper::AccessToken.where(
        application_id: application_id,
        resource_owner_id: resource.id,
        revoked_at: nil
      ).order(:created_at).last

      if !token || token.expired?
        token = Doorkeeper::AccessToken.create!(
          application_id: 1,
          resource_owner_id: resource.id
        )
      end

      token
  end


  def get_token(resource, application_id)
    Doorkeeper::AccessToken.where(application_id: application_id,resource_owner_id: resource.id,revoked_at: nil).order(:created_at).last.token
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # before_filter :authenticate_user!, only: [:authed_request]
  doorkeeper_for :all, except: [:index]

  def index
  end

  def authed_request
    render json: {success: true, data: "it's a boy!"}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 new_day0
- if user_signed_in?
  = "Signed in as #{current_user.email}. Not you?"
  = link_to "Sign out", "http://33.33.33.70:81"+destroy_user_session_path,:method => :delete
- else
  = link_to "Sign up", new_user_registration_path
  or
  = link_to "Sign in", new_user_session_path
  = link_to "Sign in with Facebook", "http://33.33.33.70:81"+user_omniauth_authorize_path(:facebook)

%h2 Ajax Links  
- if user_signed_in?
  = "Signed in as #{current_user.email}. Not you?"
  = link_to "Sign out (not yet ajax)", "http://33.33.33.70:81"+destroy_user_session_path,:method => :delete
- else
  = link_to "Sign up (ajax and json)", ajax_registration_new_path
  <br />
  = link_to "Sign up (just json)", json_registration_new_path
  <br/ >or<br />
  = link_to "Sign in", ajax_session_new_path
  <br />
  = link_to "Sign in with Facebook (not yet ajax)", user_omniauth_authorize_path(:facebook)

%h2 Authed Request
= link_to "Make an authed request", "http://33.33.33.70:81"+authed_request_path, remote: true, id: "authed_request"

:javascript
  $(document).ready(function(){
    $("#authed_request").bind("ajax:success", function(event, data, status, xhr){
       alert("here is the authed_request return");
       alert(data)
    }).bind("ajax:error", function(event, data, status, xhr){
       alert("error, here is the authed_request error return");  
       alert(data)
    });
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewDay0</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>